version: '3'

services:
  api:
    image: travel_agency_api
    container_name: server
    build:
      context: ./TravelAgencyAPI
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerEnv
      - DATABASE_CONNECTION_STRING=Server=mssql-server;Database=travel_agency;User Id=SA;Password=Test1234;TrustServerCertificate=True;
      - REDIS_CONNECTION_STRING=redis:6379
    ports:
      - "5113:5113"
    depends_on:
      - database
      - redis
  

  auxiliary_server:
    image: travel_agency_auxiliary_server
    container_name: auxiliary_server
    build:
      context: ./TravelAgencyService
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=DockerEnv
    ports:
      - "5102:5102"

  client:
    image: travel_agency_client
    container_name: client
    build:
      context: ./travel_agency_front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=DockerEnv
      - SERVER_ADDRESS=http://server:5113


  database:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-server
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
    ports:
      - "1433:1433"
    volumes:
      - ./database/db_data:/var/opt/mssql/data
  
  
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"